### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by LeonColt** [muhammadmateen027/gender_picker#3]

**Comment by LeonColt** [comment]
@muhammadmateen027 
would you like to publish null safety to pub.dev?
Great work for the package.
Thanks you very much.

**Comment by muhammadmateen027** [comment]
> @muhammadmateen027
> would you like to publish null safety to pub.dev?
> Great work for the package.
> Thanks you very much.

Yes, Sorry for delay. Tomorrow I'll do that.

**Comment by muhammadmateen027** [comment]
Hi @LeonColt , you may proceed. I've update the plugin
